blueprint:
  name: PV Überschuss -> Steckdose steuern (separate Verzögerungen)
  description: >
    Schaltet eine Steckdose basierend auf dem PV-Überschuss ein/aus.
    Mit separater Verzögerung für Einschalten und Ausschalten, um Flattern zu vermeiden.
  domain: automation
  input:
    pv_sensor:
      name: PV Überschuss Sensor
      description: Wähle den Template-Sensor für den Überschuss aus.
      selector:
        entity:
          domain: sensor
    switch_device:
      name: Steckdose
      description: Steckdose, die geschaltet werden soll.
      selector:
        entity:
          domain: switch
    upper_threshold:
      name: Einschalt-Schwelle (W)
      description: Ab welchem Überschuss die Steckdose eingeschaltet wird.
      default: 500
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: W
          mode: box
    lower_threshold:
      name: Ausschalt-Schwelle (W)
      description: Unter welchem Überschuss die Steckdose ausgeschaltet wird.
      default: 100
      selector:
        number:
          min: -10000
          max: 10000
          unit_of_measurement: W
          mode: box
    delay_on:
      name: Verzögerung Einschalten (Sekunden)
      description: Zeit, die der Überschuss über der Einschalt-Schwelle bleiben muss.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: s
          mode: box
    delay_off:
      name: Verzögerung Ausschalten (Sekunden)
      description: Zeit, die der Überschuss unter der Ausschalt-Schwelle bleiben muss.
      default: 30
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: s
          mode: box

trigger:
  - platform: numeric_state
    entity_id: !input pv_sensor
    above: !input upper_threshold
    for:
      seconds: !input delay_on
  - platform: numeric_state
    entity_id: !input pv_sensor
    below: !input lower_threshold
    for:
      seconds: !input delay_off

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input upper_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_device
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            below: !input lower_threshold
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switch_device

mode: single
